### ISSUE TITLE
Update to 1.9i

### ISSUE THREAD

**Issue by EvilOlaf** [steveg-io/pstones-modded#1]
Hi there,

I think you modifications are pretty nice.
Do you think you could update it to the latest 1.9i?

Best regards
Olaf

**Comment by EvilOlaf** [comment]
Or even add support for UUIDs?

**Comment by steveg-io** [comment]
Hey, sorry man but I am not too into Minecraft anymore. Maybe someone else could help. Best of luck :smile:

**Comment by EvilOlaf** [comment]
Did not expect an answer. Thanks for clarifying :D
